### ISSUE TITLE
I met an error

### ISSUE THREAD

**Issue by czbebe** [HallBlazzar/VGG16ConvolutionalAutoEncoder#1]
Hi, I met an error.

File "/home/oka/VGG16ConvolutionalAutoEncoder-master/DataGenerator.py", line 114, in __expand_and_standardize
    converted_data_list = data_list.astype(np.float32)
ValueError: setting an array element with a sequence

I think definition of list vs. array is confusing. 

Oka

**Comment by HallBlazzar** [comment]
Hi, czbebe

Sorry for replying you too late.
Can you give me more information about data source you used?
In my environment, as README.md shows, training and testing data are image files and separated by subdirectory under `data_source` folder.
I think the error must caused by passing wrong format of data to `base_data_source_dir` in main function.
